package com.xx.demoproject.demofactory.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xx.demoproject.demofactory.db.Gear;
import com.xx.demoproject.demofactory.db.User;

import com.xx.demoproject.demofactory.db.GearDao;
import com.xx.demoproject.demofactory.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gearDaoConfig;
    private final DaoConfig userDaoConfig;

    private final GearDao gearDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gearDaoConfig = daoConfigMap.get(GearDao.class).clone();
        gearDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        gearDao = new GearDao(gearDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Gear.class, gearDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        gearDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public GearDao getGearDao() {
        return gearDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
